[ 🚧 WIP ] added check-vowel.r
codinasion/codinasion pull request #1808
Opened 2022-10-04 18:52 UTC by YaSh8202

Closes #1776 

### What's being changed:
Added check-vowel.r

2022-10-06 15:54 UTC, victoriacheng15 requested changes

2022-10-06 15:54 UTC, victoriacheng15 commented on program/check-vowel/check_vowel.r
> +    if(char %in% c('a', 'e', 'i', 'o', 'u'))
This only check lower cases of vowels.

2022-10-08 16:55 UTC, victoriacheng15 approved these changes
Looks good!

Thank you for contributing! 👍

2022-10-08 23:17 UTC, harshraj8843 approved these changes
Thanks for contributing 👍🏻

2022-10-08 23:17 UTC, merged