write a Typescript function that calculates the surface area of a cube
codinasion/codinasion pull request #1947
Opened 2022-10-05 02:47 UTC by nickdark

### Why:

Closes #1946 

### What's being changed:
Add a Typescript function that calculates the surface area of a cube

2022-10-05 03:11 UTC, MuhammadJufri requested changes

2022-10-05 03:11 UTC, MuhammadJufri commented on program/find-surface-area-of-a-cube/findSurfaceAreaOfCube.ts
> +findSurfaceAreaOfCube(2)
You forgot to console the function

2022-10-06 02:48 UTC, nickdark commented on program/find-surface-area-of-a-cube/findSurfaceAreaOfCube.ts
> +findSurfaceAreaOfCube(2)
The change has been made.

2022-10-06 16:31 UTC, victoriacheng15 approved these changes
Nicely done!

Thank you for contributing! 👍

2022-10-06 16:32 UTC, merged