Added solution for find-area-of-a-right-angled-triangle in PHP
codinasion/codinasion pull request #2365
Opened 2022-10-08 22:23 UTC by PoweredByCaffein

### Why:

Closes #756 

### What's being changed:
Added the solution in PHP

2022-10-09 01:57 UTC, grraghav120 approved these changes

2022-10-10 15:52 UTC, victoriacheng15 requested changes
See my comment about link `language-specific` issue.

2022-10-10 17:30 UTC, PoweredByCaffein commented
Hi @victoriacheng15,
Made the changes as you asked.

2022-10-10 18:01 UTC, victoriacheng15 approved these changes

2022-10-10 18:01 UTC, merged