done with this program
codinasion/codinasion pull request #3450
Opened 2022-10-12 09:11 UTC by AmanjeetCogoport

### Why:

Closes #13

### What's being changed:

2022-10-13 22:00 UTC, victoriacheng15 requested changes, later dismissed

2022-10-13 22:00 UTC, victoriacheng15 commented on program/print-hello-world/print_hello_world.pl
> +print "Enter a number: ";
This doesn't print "Hello world !!!"

2022-10-17 20:58 UTC, harshraj8843 approved these changes, later dismissed
Thanks for contributing 👍🏻

2022-10-17 21:01 UTC, harshraj8843 approved these changes

2022-10-17 21:03 UTC, merged