Added Convert Minutes to Hours in JavaScript
codinasion/codinasion pull request #3641
Opened 2022-10-12 20:30 UTC by sidharthbh8

### Why:

Closes #3511

### What's being changed:

Added Convert Minutes to Hours in JavaScript

2022-10-12 20:33 UTC, sidharthbh8 reviewed
reviewed

2022-10-12 20:36 UTC, sidharthbh8 commented
@joao-vitor-souza  can you tell me why its showing merging blocked

2022-10-14 16:31 UTC, victoriacheng15 requested changes, later dismissed

2022-10-14 16:31 UTC, victoriacheng15 commented on program/ConvertMinutesToHours.js
> +console.log(`${ConvertMinutesToHours(60)}Hours`);
The output is `1hours`.  You can make it output `hour` or `hours` based on the result you get.

2022-10-14 16:32 UTC, victoriacheng15 commented
> @joao-vitor-souza can you tell me why its showing merging blocked

This PR was not reviewed by one of us yet.

2022-11-05 05:37 UTC, harshraj8843 approved these changes
Thanks for contributing 👍🏻

2022-11-05 05:38 UTC, merged