Go solutions
codinasion/codinasion pull request #3916
Opened 2022-10-13 19:47 UTC by PoweredByCaffein

### Why:

Closes #3352 
Closes #3650 
Closes #3676 
Closes #3700 

### What's being changed:

2022-10-14 18:26 UTC, MadhuS-1605 requested changes

2022-10-14 18:26 UTC, MadhuS-1605 commented on program/convert-seconds-to-days/convert_seconds_to_days.go
> +	var input int
I suggest you make input as float value because even 86399 input gives you value as 0 but let's get some value as input

2022-10-29 09:42 UTC, PoweredByCaffein commented
Hi @MadhuS-1605,

Added the requested changes and now printing the output up to 5 decimal places.

2022-10-29 11:01 UTC, MadhuS-1605 approved these changes

2022-10-29 11:02 UTC, merged