PrintDiamondPattern
codinasion/codinasion pull request #4892
Opened 2022-12-06 11:07 UTC by anandfresh

### Why:

Closes #ISSUE_NUMBER

### What's being changed:

2022-12-06 14:17 UTC, tanishq-singh-2301 requested changes
please mention the issue number with it

2022-12-06 14:24 UTC, joao-vitor-souza commented on program/print-diamond-pattern/PrintDiamondPattern.js
> +diamondPattern(11);
```suggestion
diamondPattern(5);
```

2022-12-06 14:25 UTC, joao-vitor-souza requested changes

2022-12-06 14:25 UTC, joao-vitor-souza commented on program/print-diamond-pattern/PrintDiamondPattern.js
> +      const layer = ' '.repeat(++iteration)+'*'.repeat(n);
Change to this, so it'll work as shown in #4674

```suggestion
   let iteration = 0;
   const construct = ['*'.repeat(2 * n - 1)];
   n *= 2;
   while ((n -= 2) > 0) {
      const layer = ' '.repeat(++iteration) + '*'.repeat(n - 1);
```

2022-12-06 14:32 UTC, joao-vitor-souza commented
I've linked the issue for you, but you need to assign it to yourself. To do this you have to comment `!assign` in #4674

2022-12-07 08:49 UTC, anandfresh commented
issue: https://github.com/codinasion/program/issues/4674

2022-12-07 08:51 UTC, oyetanishq approved these changes

2022-12-07 15:04 UTC, joao-vitor-souza approved these changes

2022-12-07 15:06 UTC, merged