Factorial of a given number
codinasion/codinasion pull request #4893
Opened 2022-12-06 11:10 UTC by anandfresh

### Why:

Closes #ISSUE_NUMBER

### What's being changed:

2022-12-06 14:18 UTC, tanishq-singh-2301 requested changes
please mention issue number with this pr

2022-12-06 14:51 UTC, joao-vitor-souza commented
Your program closes #794, and you were trying to close #3206. Also, you need to assign #794 to yourself.

2022-12-07 08:24 UTC, anandfresh commented
> please mention issue number with this pr

added the issue number  #3206 
https://github.com/codinasion/program/issues/3206

2022-12-07 08:53 UTC, tanishq-singh-2301 approved these changes

2022-12-07 08:53 UTC, merged