Program/print ascii value of a character
codinasion/codinasion pull request #4900
Opened 2022-12-07 06:57 UTC by kishoredubey

### Why:

Closes #https://github.com/codinasion/program/issues/4148

### What's being changed:

2022-12-08 03:08 UTC, kishoredubey commented
re-opened the PR, please review.

2022-12-08 07:27 UTC, anandfresh requested changes

2022-12-09 03:27 UTC, harshraj8843 commented on program/print-ascii-value-of-a-character/PrintAsciiValueOfACharacter.kt
> +fun ascii(first: Char) = first.code
Can be updated later 👍🏻

2022-12-09 03:28 UTC, harshraj8843 approved these changes
Thanks for contributing 👍🏻

2022-12-09 03:28 UTC, merged