Program of sum of squares of number
codinasion/codinasion pull request #5359
Opened 2022-12-09 17:23 UTC by shauryag2002

### Why:

#5250 
Program of sum of squares of number

Closes #ISSUE_NUMBER

### What's being changed:

2022-12-09 17:57 UTC, anandfresh requested changes

2022-12-09 17:57 UTC, anandfresh commented on program/program-to-find-sum-of-all-numbers-in-array/FindSumOfSquaresOfNumbers.js
> +    count=count+(b[i]*b[i]);
why do you want to prompt in a loop ?

2022-12-09 17:57 UTC, anandfresh commented on program/program-to-find-sum-of-all-numbers-in-array/FindSumOfSquaresOfNumbers.js
> +console.log(count)
Instead of prompting , can you write a function passing number as an argument

2022-12-09 17:58 UTC, anandfresh reviewed
Thumb rule : Get yourself assign to the issue before raising a PR

2022-12-09 18:14 UTC, victoriacheng15 commented
@shauryag2002 you also need to link the correct issue.

2022-12-10 02:26 UTC, harshraj8843 commented
Hey @shauryag2002 

Issue codinasion/codinasion#1669 has already been closed

Few improvements you can do for your future contributions:
- Please be auto-assigned on the issue you want to contribute by commenting `!assign`, to prevent any conflict
- Please add the program to specific folder as suggested in the respective issue
- Please use `Closes #IssueNumber` while creating PR (e.g. `Closes codinasion/codinasion#106`)

Thanks for contributing 👍🏻

2022-12-10 02:26 UTC, closed without merging