Create `MergeTwoStrings.js`
codinasion/codinasion pull request #5531
Opened 2022-12-10 02:44 UTC by Dcastro99

### Why:

#5432

### What's being changed:

added function mergeTwoStrings

2022-12-10 02:50 UTC, anandfresh approved these changes

2022-12-10 02:52 UTC, anandfresh requested changes

2022-12-10 02:52 UTC, anandfresh commented on program/merge-two-strings/MergeTwoStrings.js
> +mergeStrings();
can you pass the string which is given in the issue as an argument while invoking the function 
`console.log(mergeStrings('ABC', 'DEF'));`

2022-12-12 03:58 UTC, joao-vitor-souza approved these changes

2022-12-12 04:00 UTC, joao-vitor-souza approved these changes

2022-12-12 09:25 UTC, anandfresh approved these changes

2022-12-12 09:25 UTC, merged