add function to calcuate volume of a cylinder in js, go, php, py, c, …
codinasion/codinasion pull request #5532
Opened 2022-12-10 02:49 UTC by Edward-Regalado

…cpp, cs, java, rb, scala and ts

### Why: #5390

Closes #ISSUE_NUMBER

### What's being changed:

2022-12-10 02:55 UTC, anandfresh requested changes
Can you add the issue id's for all the 11 different language files .
Currently you have attached only for Javascript

2022-12-10 02:59 UTC, harshraj8843 commented
Hey @Edward-Regalado 

Please comment `!assign` on all the linked issue, to be auto-assigned, to prevent any conflict 👍🏻

2022-12-10 03:01 UTC, anandfresh requested changes
@Edward-Regalado  Can you pls make sure you have assigned to the issues you have mentioned . 
I'm not seeing all the issues are assigned to you .
Thumb rule : Assign your issues before creating a PR

2022-12-10 04:11 UTC, Edward-Regalado commented
@anandfresh My apologies. I went ahead and assigned myself on all linked issues from above.

2022-12-10 04:27 UTC, anandfresh requested changes

2022-12-10 04:27 UTC, anandfresh commented on program/find-volume-of-a-cylinder/volumeOfCylinder.js
> +    return volume;
can we round of the volume result ?

2022-12-10 04:27 UTC, anandfresh commented on program/find-volume-of-a-cylinder/find_volume_of_a_cylinder.php
> +  return $volume;
round of the volume

2022-12-10 04:27 UTC, anandfresh commented on program/find-volume-of-a-cylinder/find_volume_of_a_cylinder.go
> +  return volume
round of the volume

2022-12-10 04:27 UTC, anandfresh commented on program/find-volume-of-a-cylinder/findVolumeOfACylinder.scala
> +  volume
round of the volume to two decimals

2022-12-10 04:27 UTC, anandfresh commented on program/find-volume-of-a-cylinder/findVolumeOfACylinder.rb
> +    volume
round of the volume to two decimals

2022-12-10 04:27 UTC, anandfresh commented on program/find-volume-of-a-cylinder/find-volume-of-a-cylinder.py
> +  return volume
round of the volume to two decimals

2022-12-10 04:27 UTC, anandfresh commented on program/find-volume-of-a-cylinder/FindVolumeOfACylinder.ts
> +  }
round of the volume to two decimals

2022-12-10 04:27 UTC, anandfresh commented on program/find-volume-of-a-cylinder/FindVolumeOfACylinder.java
> +        return volume;
round of the volume to two decimals

2022-12-10 04:27 UTC, anandfresh commented on program/find-volume-of-a-cylinder/FindVolumeOfACylinder.cs
> +    }
round of the volume to two decimals

2022-12-10 04:27 UTC, anandfresh commented on program/find-volume-of-a-cylinder/FindVolumeOfACylinder.cpp
> +}
round of the volume to two decimals

2022-12-10 04:27 UTC, anandfresh commented on program/find-volume-of-a-cylinder/FindVolumeOfACylinder.c
> +}
round of the volume to two decimals

2023-01-11 17:01 UTC, harshraj8843 approved these changes
Thanks for contributing and sorry for the delay 🤗

2023-01-11 17:02 UTC, merged