Finished task to convert inches to feet
codinasion/codinasion pull request #5671
Opened 2022-12-11 04:56 UTC by gtierrezandres

### Why:

Closes #5631 

### What's being changed:
Added `convert-inches-to-feet.py` under `program/convert-inches-to-feet`

2022-12-11 05:07 UTC, anandfresh requested changes

2022-12-11 05:07 UTC, anandfresh commented on program/convert-inches-to-feet/convert-inches-to-feet.py
> +print(inches/12)
can you round off the result to two decimals ?

2022-12-12 04:03 UTC, joao-vitor-souza approved these changes

2022-12-12 04:55 UTC, anandfresh approved these changes

2022-12-12 04:55 UTC, merged