added program of print numbers from 1 to n
codinasion/codinasion pull request #5678
Opened 2022-12-11 11:23 UTC by shauryag2002

### Why:

Closes #5207

### What's being changed:

2022-12-11 14:17 UTC, anandfresh requested changes
You have two programs combined in this PR . 
Can you add the issue ID for the other program 'FindSumOfSquaresOfNumbers.js'.

2022-12-11 14:18 UTC, anandfresh requested changes

2022-12-11 14:18 UTC, anandfresh commented on program/program-to-find-sum-of-all-numbers-in-array/FindSumOfSquaresOfNumbers.js
> +
why prompting inside the loop ?

2022-12-17 14:58 UTC, harshraj8843 commented on program/program-to-find-sum-of-all-numbers-in-array/FindSumOfSquaresOfNumbers.js
> +
for elements

2022-12-17 15:01 UTC, harshraj8843 approved these changes
Thanks for contributing 👍🏻

2022-12-18 10:11 UTC, anandfresh approved these changes

2022-12-18 10:11 UTC, merged