finished working the rotate matrix challenge
codinasion/codinasion pull request #5698
Opened 2022-12-12 18:27 UTC by SarahTek

### Why:

Closes #ISSUE_NUMBER

### What's being changed:

2022-12-12 19:04 UTC, victoriacheng15 commented
@SarahTek 

Please link the issue number.

2022-12-13 15:20 UTC, victoriacheng15 requested changes
`j is not defined` after ran it.

![image](https://user-images.githubusercontent.com/35031228/207372776-e2fa6cb5-425a-4bd2-aecf-ca9e37af1e77.png)

2022-12-14 04:59 UTC, anandfresh requested changes, later dismissed

2022-12-14 04:59 UTC, anandfresh commented on program/cylindrically-rotate-a-matrix-by-90-degrees/rotateMatrix.js
> +rotate90Clockwise(arr);
This code won't work in a strict mode . 
Either you need to remove 'using strict' or fix the variable j declaration

2022-12-17 19:35 UTC, victoriacheng15 approved these changes

2022-12-17 21:42 UTC, merged