Cube root
codinasion/codinasion pull request #5900
Opened 2022-12-31 20:44 UTC by anandfresh

Issue: https://github.com/codinasion/program/issues/4231
### Why:

Closes #4231

### What's being changed:

2023-01-01 16:16 UTC, tanishq-singh-2301 requested changes

2023-01-01 16:16 UTC, tanishq-singh-2301 commented on program/find-cube-root-of-a-number/FindCubeRootOfANumber.rb
> + return pow($n, 1/3) ;
remove that extra space

2023-01-01 16:18 UTC, tanishq-singh-2301 approved these changes

2023-01-03 16:28 UTC, victoriacheng15 approved these changes

2023-01-03 16:28 UTC, merged