split-string-to-arraoOfSTrings-swift
codinasion/codinasion pull request #5918
Opened 2023-01-01 11:10 UTC by sahilg2931

### Why:

Closes #ISSUE_NUMBER

### What's being changed:

2023-01-01 11:14 UTC, anandfresh requested changes
@sahilg2931 Please add the issue ID to this PR.

2023-01-01 13:52 UTC, sahilg2931 commented
@anandfresh  issue id attached

2023-01-02 13:42 UTC, anandfresh requested changes

2023-01-02 13:42 UTC, anandfresh commented on program/split-string-into-array-of-words/split_string_into_array_of_words.swift
> +   print("String of array is  \(inputData)!")
What is inputData ? It is not in the scope .

2023-01-07 08:38 UTC, anandfresh approved these changes

2023-01-11 16:04 UTC, harshraj8843 approved these changes
Thanks for contributing 👍🏻

2023-01-11 16:04 UTC, merged

2023-01-12 06:08 UTC, sahilg2931 commented
Thanks a lot, look forward to making more contributions this year in the OS.