convertFahrenheitToCelsius in python
codinasion/codinasion pull request #5935
Opened 2023-01-02 22:17 UTC by Medmly20208

### Why:

Closes #5027 

### What's being changed:

2023-01-03 02:45 UTC, anandfresh requested changes
@Medmly20208 please assign the issue (https://github.com/codinasion/program/issues/5027) to your name before raising a PR

2023-01-03 07:03 UTC, Medmly20208 commented
@anandfresh I just did

2023-01-03 07:47 UTC, anandfresh approved these changes

2023-01-11 16:11 UTC, harshraj8843 approved these changes
Thanks for contributing 👍🏻

2023-01-11 16:11 UTC, merged