convertion decimal to binary
codinasion/codinasion pull request #5939
Opened 2023-01-03 11:39 UTC by Emilia-mazari

### Why:
Closes #3846 

### What's being changed:

2023-01-04 06:11 UTC, anandfresh requested changes
@Emilia-mazari  , Please assign this issue ( https://github.com/codinasion/program/issues/3846) to your name before raising a PR

2023-01-05 02:53 UTC, anandfresh requested changes

2023-01-05 02:53 UTC, anandfresh commented on program/convert-decimal-to-binary/ConversationToBinAndDec.java
> +//
remove the unwanted code comments

2023-01-08 08:16 UTC, hi-Kartik2004 reviewed
Hi @Emilia-mazari ✋🏻 , Thanks for linking the issue and making a Pull request (PR) but I'm **getting an error when I try to compile your file.**
The same is attached to this comment, can you resolve this? 
, and I shall approve the changes.😄 
![image](https://user-images.githubusercontent.com/111000515/211186698-59b05ce3-bc95-4fdf-acdc-3ac3f9069db8.png)

2023-01-11 16:47 UTC, hi-Kartik2004 approved these changes

2023-01-11 16:58 UTC, harshraj8843 approved these changes
Thanks for contributing 👍🏻

2023-01-11 16:58 UTC, merged