Solves #5644
codinasion/codinasion pull request #5950
Opened 2023-01-04 16:14 UTC by vedantpople4

### Why:

Closes #5644

### What's being changed:
Added code to split a string into an array of words in GO

2023-01-05 02:46 UTC, anandfresh requested changes
@vedantpople4  Please assign this issue (#5644) to your name and make sure to assign the issues to your name before raising a PR

2023-01-05 04:21 UTC, vedantpople4 commented
Assignment Done

2023-01-06 05:16 UTC, anandfresh approved these changes

2023-01-08 08:59 UTC, hi-Kartik2004 approved these changes

2023-01-08 08:59 UTC, merged