Find smallest number in a array in cpp
codinasion/codinasion pull request #5964
Opened 2023-01-06 16:08 UTC by hi-Kartik2004

### Why:
Closes codinasion/codinasion#2912 
Closes codinasion/codinasion#3759

### What's being changed:
Added a C++ file to find the smallest number in an array.

2023-01-07 02:52 UTC, anandfresh requested changes
@hi-Kartik2004  , This PR has two file changes , but you have added only one issue ID .
Can you please add the issue id for finding the power of a number

2023-01-07 03:02 UTC, anandfresh commented
> @hi-Kartik2004 , This PR has two file changes , but you have added only one issue ID . Can you please add the issue id for finding the power of a number

I just updated the issue id's

2023-01-07 03:05 UTC, anandfresh approved these changes

2023-01-11 16:41 UTC, harshraj8843 approved these changes
Thanks for contributing 👍🏻

2023-01-11 16:42 UTC, merged