Add print_reverse_of_a_number_by_recursion.dart
codinasion/codinasion pull request #6038
Opened 2023-01-18 15:11 UTC by james-tharit

### Why:

Closes #5558

### What's being changed:

Added` print_reverse_of_a_number_by_recursion.dart`

2023-01-18 18:04 UTC, tanishq-singh-2301 approved these changes

2023-01-18 19:41 UTC, joao-vitor-souza requested changes
It fails to reverse a number that starts or ends in a sequence of zeros. Example:

```python
Input: 123000
Output: 321

Input: 00120
Output: 21
```

As a workaround, I think you'll probably have to use an approach that converts the numbers into characteres and prints them as strings.

2023-01-19 01:51 UTC, james-tharit commented
Thanks for reviewing this, I will push the fixed soon.

2023-01-19 02:46 UTC, james-tharit commented
@joao-vitor-souza  fixed has been push 😀

2023-01-19 06:52 UTC, anandfresh approved these changes

2023-01-19 18:58 UTC, joao-vitor-souza approved these changes

2023-01-19 19:00 UTC, merged