Average of digits
codinasion/codinasion pull request #6081
Opened 2023-01-23 13:52 UTC by Coder-12-ux

### Why:

Closes #5371 

### What's being changed:

2023-01-23 16:34 UTC, anandfresh requested changes

2023-01-23 16:34 UTC, anandfresh commented on program/find-average-of-digits-of-a-number/FindAverageOfDigitsOfANumberByRecursion.kt
> +import java.util.Scanner
@Coder-12-ux rename the file , you have used the same file name for both recursion and non-recursion

2023-01-23 16:36 UTC, hi-Kartik2004 commented
Hi @Coder-12-ux, Firstly thanks for making a PR (pull request) I see that you have linked only one issue, can you link both issues by editing your first / main comment with 

closes #`issuenumber1`
closes #`issuenumber2`

2023-01-24 05:03 UTC, harshraj8843 approved these changes
Thanks for contributing 🤗

2023-01-24 06:44 UTC, hi-Kartik2004 approved these changes

2023-01-24 06:54 UTC, merged