Finding the surface area of the cuboid in C.
codinasion/codinasion pull request #6641
Opened 2023-03-09 09:23 UTC by Sri01729

### Why:

Closes #4454 

### What's being changed:

Updated required code for finding the surface area of the cuboid.

2023-03-09 16:11 UTC, pokharel-nishan approved these changes

2023-03-12 09:00 UTC, hi-Kartik2004 approved these changes

2023-03-12 09:01 UTC, hi-Kartik2004 requested changes, later dismissed
The same problem in 'C' already exists

2023-03-17 09:19 UTC, anandfresh approved these changes

2023-03-17 09:21 UTC, harshraj8843 approved these changes
Thanks for contributing 🤗

2023-03-17 09:22 UTC, merged