Write a R program to check anagram string #6657
codinasion/codinasion pull request #6699
Opened 2023-03-17 09:43 UTC by Preetiraj3697

Closes #6657

2023-03-17 16:00 UTC, hi-Kartik2004 requested changes
Hi @Preetiraj3697, firstly thanks for making a pull request which closes 2 issues, but your comment says you are fixing a single issue, can you link all the issues you're fixing to the first comment?

Format: Closes  (issue number goes here)

2023-03-18 08:26 UTC, Preetiraj3697 commented on program/print-elements-of-an-array/PrintElementsOfAnArray.fs
Close issue #5470

2023-03-18 08:28 UTC, Preetiraj3697 commented on program/check-anagram-string/write_a_program_to_check_anagram_string.r
Close issue #6657

2023-03-18 08:31 UTC, Preetiraj3697 commented
> Hi @Preetiraj3697, firstly thanks for making a pull request which closes 2 issues, but your comment says you are fixing a single issue, can you link all the issues you're fixing to the first comment?
> 
> Format: Closes (issue number goes here)

I add it. 
Close issue #6657  (Write a R program to check anagram string )
Close issue #5470 (Write a F# program to print elements of an array)

2023-03-18 10:22 UTC, Preetiraj3697 commented on program/merge-two-strings/MergeTwoStrings.fs
Close issue #5428 program to merge two strings

2023-03-19 03:46 UTC, hi-Kartik2004 approved these changes

2023-03-19 03:46 UTC, merged