Seconds to minutes
codinasion/codinasion pull request #7343
Opened 2023-04-17 18:23 UTC by anandfresh

### Why:

Closes #357

### What's being changed:

2023-04-18 13:54 UTC, victoriacheng15 requested changes

2023-04-18 13:54 UTC, victoriacheng15 commented on program/convert-seconds-to-minutes/convert_seconds_to_minutes.dart
> +  var seconds =int.parse(stdin.readLineSync());
![image](https://user-images.githubusercontent.com/35031228/232799462-1e834764-9bfe-4772-9620-b9810e9a7970.png)

Got this error instead

2023-04-19 07:23 UTC, anandfresh commented on program/convert-seconds-to-minutes/convert_seconds_to_minutes.dart
> +  var seconds =int.parse(stdin.readLineSync());
@victoriacheng15  I used to check it in https://replit.com/ . Its working fine in replit online compiler .
Pls check again in this compiler

2023-04-19 14:21 UTC, victoriacheng15 commented on program/convert-seconds-to-minutes/convert_seconds_to_minutes.dart
> +  var seconds =int.parse(stdin.readLineSync());
still got an error with replit

![image](https://user-images.githubusercontent.com/35031228/233105113-81670556-401d-48f8-8848-a6e6d2b83ea7.png)

2023-04-22 18:11 UTC, anandfresh commented on program/convert-seconds-to-minutes/convert_seconds_to_minutes.dart
> +  var seconds =int.parse(stdin.readLineSync());
@victoriacheng15 can you retest now

2023-04-22 18:28 UTC, victoriacheng15 approved these changes
Thank you for fixing!

2023-04-22 18:28 UTC, merged