Conversion from Paise to Rupees in JS file
codinasion/codinasion pull request #846
Opened 2022-10-02 17:00 UTC by Greeshma-frontier

Closes #822 

### What's being changed:

Added JS file to convert Paise to Rupees

2022-10-02 21:30 UTC, victoriacheng15 approved these changes
looks good! 

thank you for contributing!

2022-10-03 18:21 UTC, harshraj8843 requested changes
Please update file name

2022-10-04 15:06 UTC, victoriacheng15 approved these changes
Looks good!

Thank you for contributing!

2022-10-06 02:24 UTC, harshraj8843 approved these changes
Thanks for contributing 👍🏻

2022-10-06 02:24 UTC, merged